#!/usr/bin/env python3
"""Convert monochrome BMPs in this folder to PROGMEM arrays."""
from __future__ import annotations

import argparse
import math
import pathlib
from typing import List

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
PIC_DIR = ROOT / "pics"
OUTPUT = ROOT / "src" / "PICsData.h"

BITMAP_ORDER = ["br00.bmp", "br01.bmp", "br02.bmp"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert BMP assets into SSD1306 bitmap data."
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Render PNG previews of the generated bitmaps for verification.",
    )
    parser.add_argument(
        "--invert",
        action="store_true",
        help="Invert bits so white/black swap relative to the source.",
    )
    return parser.parse_args()


def pack_bitmap(img: Image.Image, invert: bool) -> List[int]:
    img = img.convert("1")
    width, height = img.size
    pixels = img.load()
    data: List[int] = []
    for y in range(height):
        byte = 0
        bit_index = 0
        for x in range(width):
            bit_val = 0 if pixels[x, y] else 1
            if invert:
                bit_val ^= 1
            if bit_val:
                byte |= 1 << bit_index
            bit_index += 1
            if bit_index == 8:
                data.append(byte)
                byte = 0
                bit_index = 0
        if bit_index:
            data.append(byte)
    return data


def format_bytes(values: List[int], per_line: int = 12) -> str:
    hexes = [f"0x{value:02X}" for value in values]
    lines = []
    for i in range(0, len(hexes), per_line):
        chunk = ", ".join(hexes[i : i + per_line])
        lines.append(f"\t{chunk}")
    return ",\n".join(lines)


def build_header(entries) -> str:
    header_lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by pics/convert_bitmaps.py -- do not edit manually.",
        "",
    ]

    array_names = []
    for name, width, height, data in entries:
        array_name = f"epd_bitmap_{name}"
        array_names.append(array_name)
        header_lines.append(f"// '{name}', {width}x{height}px")
        header_lines.append(f"const unsigned char {array_name}[] PROGMEM = {{")
        header_lines.append(format_bytes(data))
        header_lines.append("};")
        header_lines.append("")

    header_lines.append(f"const int epd_bitmap_allArray_LEN = {len(array_names)};")
    header_lines.append("const unsigned char* const epd_bitmap_allArray[] = {")
    for name in array_names:
        header_lines.append(f"\t{name},")
    header_lines.append("};")
    header_lines.append("")
    return "\n".join(header_lines)


def save_preview(
    name: str, width: int, height: int, data: List[int], invert: bool
) -> None:
    image = Image.new("1", (width, height), color=1 if invert else 0)
    pixels = image.load()
    row_stride = math.ceil(width / 8)
    idx = 0
    for y in range(height):
        for byte_index in range(row_stride):
            if idx >= len(data):
                break
            byte = data[idx]
            idx += 1
            for bit in range(8):
                x = byte_index * 8 + bit
                if x >= width:
                    break
                bit_on = ((byte >> bit) & 0x01) == 1
                pixels[x, y] = 0 if bit_on else 1
    preview_path = PIC_DIR / f"{name}_preview.png"
    image.save(preview_path)
    print(f"Preview saved to {preview_path}")


def main() -> None:
    args = parse_args()
    entries = []
    for filename in BITMAP_ORDER:
        path = PIC_DIR / filename
        if not path.exists():
            raise FileNotFoundError(path)
        image = Image.open(path)
        width, height = image.size
        data = pack_bitmap(image, args.invert)
        name = filename.split(".")[0]
        entries.append((name, width, height, data))
        if args.preview:
            save_preview(name, width, height, data, args.invert)

    header = build_header(entries)
    try:
        OUTPUT.write_text(header)
    except OSError as exc:
        print(f"[WARN] {exc}; writing header to stdout instead. Copy manually if needed.\n")
        print(header)
    else:
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
